### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by siddhpuraamitr** [Seyz123/node-apktool#1]
Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/https%3A//github.com/Seyz123/node-apktool.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

**Comment by Seyz123** [comment]
Hello, try using : `npm install --save github:Seyz123/node-apktool`.
